### ISSUE TITLE
Compatibility with Anki 2.1.32

### ISSUE THREAD

**Issue by DannyWilliamsDJW** [Arthur-Milchior/anki-enhance-main-window#95] opened 2020-08-25 18:18 UTC
Hi there,
I can't get this add-on with the latest version of Anki

Please may you update it and let me know when you've done it!

I'll leave a very positive feedback!

Thanks

Danny

**Comment by Arthur-Milchior** [comment] 2020-08-25 18:49
Duplicate of https://github.com/Arthur-Milchior/anki-enhance-main-window/issues/90

**Closed by Arthur-Milchior** 2020-08-25 18:49 UTC
