### ISSUE TITLE
anki-enhance-main-window

### ISSUE THREAD

**Issue by jermeyjor** [Arthur-Milchior/anki-enhance-main-window#93] opened 2020-08-16 06:16 UTC
please fix the problem with the new version of Anki 2.1.30  ,, its says its not available for the new version

**Comment by Arthur-Milchior** [comment] 2020-08-16 07:12
This is a duplicate of https://github.com/Arthur-Milchior/anki-enhance-main-window/issues/90

**Closed by Arthur-Milchior** 2020-08-16 07:12 UTC
